package Domain.Useful;

public enum GameDataTypes {
    ATOM,
    ATOM_ALPHA,
    ATOM_BETA,
    ATOM_GAMMA,
    ATOM_SIGMA,

    MOLECULE,
    MOLECULE_ALPHA,
    MOLECULE_BETA,
    MOLECULE_GAMMA,
    MOLECULE_SIGMA,
    MOLECULE_STRUCTURE,
    MOLECULE_MOVEMENT_TYPE,

    REACTION_BLOCKER,
    BLOCKER_ALPHA,
    BLOCKER_BETA,
    BLOCKER_GAMMA,
    BLOCKER_SIGMA,

    POWER_UP,
    POWERUP_ALPHA,
    POWERUP_BETA,
    POWERUP_GAMMA,
    POWERUP_SIGMA,

    DIFFICULTY,
    LENGTH;

}
